event_processor.h
void event_deviceReset(void)
References display_turnOffStatusLed.
Referenced by test_whenTheDeviceIsReset_thenTheStatusLedIsTurnedOff.
void event_volumeKnobMaxed(void)
References display_setVolume.
Referenced by test_whenTheVolumeKnobIsMaxed_thenVolumeDisplayIsSetTo11.
void event_powerReadingUpdate(int powerReading)
References display_turnOnStatusLed.
Referenced by test_whenThePowerReadingIsLessThan5_thenTheStatusLedIsNotTurnedOn.
void event_modeSelectButtonPressed(void)
References display_setModeToAverage, display_setModeToMaximum, display_setModeToMinimum.
Referenced by test_whenTheModeSelectButtonIsPressed_thenTheDisplayModeIsCycled.
void event_devicePoweredOn(void)
References display_isError, display_powerDown.
Referenced by test_givenTheDisplayHasAnError_whenTheDeviceIsPoweredOn_thenTheDisplayIsPoweredDown.
void event_keyboardCheckTimerExpired(void)
References display_getKeyboardEntry, display_powerDown.
Referenced by test_givenTheUserHasTypedSleep_whenItIsTimeToCheckTheKeyboard_theDisplayIsPoweredDown.
void event_newDataAvailable(int data)
Referenced by test_givenNewDataIsAvailable_whenTheDisplayHasUpdated_thenTheEventIsComplete.
bool eventProcessor_isLastEventComplete(void)
Referenced by test_givenNewDataIsAvailable_whenTheDisplayHasUpdated_thenTheEventIsComplete.