nepMathCrcUtil.c
NUMBER_OF_BITS_IN_BYTE
MAX_SIZE
BITMASK
MASK
void vNepMathCrcUtilReflectData(uint8_t ucNumberOfBits, uint32_t ulData, uint32_t *pulResult)
References BITMASK.
Referenced by eNepMathCrcCalculate, eNepMathCrcValidate.
void vNepMathCrcUtilReflectBytes(uint32_t ulNumberOfBytes, const uint8_t *pucBuffer, uint8_t *pucResult)
References BITMASK, NUMBER_OF_BITS_IN_BYTE.
Referenced by eNepMathCrcCalculate, eNepMathCrcValidate.
void vNepMathCrcUtilCalculate(uint8_t ucWidth, uint32_t ulInitial, uint32_t ulPolynomial, uint32_t ulNumberOfBytes, const uint8_t *pucBuffer, uint32_t *pulCrcValue)
References BITMASK, MASK, NUMBER_OF_BITS_IN_BYTE.
Referenced by eNepMathCrcCalculate, eNepMathCrcValidate.