.TH "UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/bar.h" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/bar.h
.SH SYNOPSIS
.br
.PP
\fC#include 'custom_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbar_turn_on\fP (void)"
.br
.ti -1c
.RI "void \fBbar_print_message\fP (const char *message)"
.br
.ti -1c
.RI "void \fBbar_print_message_formatted\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBbar_numbers\fP (int one, int two, char three)"
.br
.ti -1c
.RI "void \fBbar_const_test\fP (const char *a, char *const b, const int c)"
.br
.ti -1c
.RI "\fBcustom_t\fP \fBbar_needs_custom_type\fP (void)"
.br
.ti -1c
.RI "const char * \fBbar_return_const_ptr\fP (int one)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bar_const_test (const char * a, char *const b, const int c)"

.SS "\fBcustom_t\fP bar_needs_custom_type (void)"

.SS "void bar_numbers (int one, int two, char three)"

.SS "void bar_print_message (const char * message)"

.SS "void bar_print_message_formatted (const char * format,  \&.\&.\&.)"

.SS "const char* bar_return_const_ptr (int one)"

.SS "void bar_turn_on (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
