.TH "Sources Directory Reference" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmpbTimeBase\&.c\fP"
.br
.RI "
.br
 This library proveies a management system for the timing of the differents process in the application\&. Each on of the timers neeeded in a application should be initialized, triggerd inside a timer interruption and read for verify his deadline\&. "
.in -1c
