.TH "Includes Directory Reference" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Includes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmpblibs\&.h\fP"
.br
.RI "This header provides common definitions needed mpb library @description\&. "
.ti -1c
.RI "file \fBmpbTimeBase\&.h\fP"
.br
.in -1c
