.TH "CEXCEPTION_FRAME_T" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CEXCEPTION_FRAME_T
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CException\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "jmp_buf * \fBpFrame\fP"
.br
.ti -1c
.RI "\fBCEXCEPTION_T\fP volatile \fBException\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file CException\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBCEXCEPTION_T\fP volatile Exception"

.PP
Definition at line 64 of file CException\&.h\&.
.SS "jmp_buf* pFrame"

.PP
Definition at line 63 of file CException\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
