.TH "UnitTestFramework/vendor/ceedling/vendor/c_exception/lib/CException.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/vendor/c_exception/lib/CException.c
.SH SYNOPSIS
.br
.PP
\fC#include 'CException\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBThrow\fP (\fBCEXCEPTION_T\fP ExceptionID)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile \fBCEXCEPTION_FRAME_T\fP \fBCExceptionFrames\fP [\fBCEXCEPTION_NUM_ID\fP] = {{ 0 }}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Throw (\fBCEXCEPTION_T\fP ExceptionID)"

.PP
Definition at line 11 of file CException\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "volatile \fBCEXCEPTION_FRAME_T\fP CExceptionFrames[\fBCEXCEPTION_NUM_ID\fP] = {{ 0 }}"

.PP
Definition at line 5 of file CException\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
