.TH "UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/display.h" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/display.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay_turnOffStatusLed\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_turnOnStatusLed\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_setVolume\fP (int level)"
.br
.ti -1c
.RI "void \fBdisplay_setModeToMinimum\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_setModeToMaximum\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_setModeToAverage\fP (void)"
.br
.ti -1c
.RI "bool \fBdisplay_isError\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_powerDown\fP (void)"
.br
.ti -1c
.RI "void \fBdisplay_updateData\fP (int data, void(*updateCompleteCallback)(void))"
.br
.ti -1c
.RI "void \fBdisplay_getKeyboardEntry\fP (char *entry, int length)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void display_getKeyboardEntry (char * entry, int length)"

.SS "bool display_isError (void)"

.SS "void display_powerDown (void)"

.SS "void display_setModeToAverage (void)"

.SS "void display_setModeToMaximum (void)"

.SS "void display_setModeToMinimum (void)"

.SS "void display_setVolume (int level)"

.SS "void display_turnOffStatusLed (void)"

.PP
Definition at line 4 of file display\&.c\&.
.SS "void display_turnOnStatusLed (void)"

.SS "void display_updateData (int data, void(*)(void) updateCompleteCallback)"

.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
