.TH "UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/display.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/display.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'display\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay_turnOffStatusLed\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void display_turnOffStatusLed (void)"

.PP
Definition at line 4 of file display\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
