.TH "UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/event_processor.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/event_processor.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'event_processor\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBevent_deviceReset\fP (void)"
.br
.ti -1c
.RI "void \fBevent_volumeKnobMaxed\fP (void)"
.br
.ti -1c
.RI "void \fBevent_powerReadingUpdate\fP (int powerReading)"
.br
.ti -1c
.RI "void \fBevent_modeSelectButtonPressed\fP (void)"
.br
.ti -1c
.RI "void \fBevent_devicePoweredOn\fP (void)"
.br
.ti -1c
.RI "void \fBevent_keyboardCheckTimerExpired\fP (void)"
.br
.ti -1c
.RI "void \fBevent_newDataAvailable\fP (int data)"
.br
.ti -1c
.RI "bool \fBeventProcessor_isLastEventComplete\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void event_devicePoweredOn (void)"

.PP
Definition at line 56 of file event_processor\&.c\&.
.SS "void event_deviceReset (void)"

.PP
Definition at line 12 of file event_processor\&.c\&.
.SS "void event_keyboardCheckTimerExpired (void)"

.PP
Definition at line 64 of file event_processor\&.c\&.
.SS "void event_modeSelectButtonPressed (void)"

.PP
Definition at line 31 of file event_processor\&.c\&.
.SS "void event_newDataAvailable (int data)"

.PP
Definition at line 84 of file event_processor\&.c\&.
.SS "void event_powerReadingUpdate (int powerReading)"

.PP
Definition at line 23 of file event_processor\&.c\&.
.SS "void event_volumeKnobMaxed (void)"

.PP
Definition at line 18 of file event_processor\&.c\&.
.SS "bool eventProcessor_isLastEventComplete (void)"

.PP
Definition at line 90 of file event_processor\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
