.TH "UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/foo.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/foo.c
.SH SYNOPSIS
.br
.PP
\fC#include 'foo\&.h'\fP
.br
\fC#include 'bar\&.h'\fP
.br
\fC#include 'subfolder/zzz\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfoo_turn_on\fP (void)"
.br
.ti -1c
.RI "void \fBfoo_print_message\fP (const char *message)"
.br
.ti -1c
.RI "void \fBfoo_print_special_message\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void foo_print_message (const char * message)"

.PP
Definition at line 10 of file foo\&.c\&.
.SS "void foo_print_special_message (void)"

.PP
Definition at line 14 of file foo\&.c\&.
.SS "void foo_turn_on (void)"

.PP
Definition at line 5 of file foo\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
