.TH "UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/test/test_foo.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/test/test_foo.c
.SH SYNOPSIS
.br
.PP
\fC#include 'unity\&.h'\fP
.br
\fC#include 'foo\&.h'\fP
.br
\fC#include 'mock_bar\&.h'\fP
.br
\fC#include 'mock_zzz\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP (void)"
.br
.ti -1c
.RI "void \fBtearDown\fP (void)"
.br
.ti -1c
.RI "void \fBtest_foo\fP (void)"
.br
.ti -1c
.RI "void \fBtest_foo_again\fP (void)"
.br
.ti -1c
.RI "void \fBtest_foo_mock_with_const\fP (void)"
.br
.ti -1c
.RI "void \fBtest_foo_mock_with_variable_args\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void setUp (void)"

.PP
Definition at line 6 of file test_foo\&.c\&.
.SS "void tearDown (void)"

.PP
Definition at line 10 of file test_foo\&.c\&.
.SS "void test_foo (void)"

.PP
Definition at line 14 of file test_foo\&.c\&.
.SS "void test_foo_again (void)"

.PP
Definition at line 25 of file test_foo\&.c\&.
.SS "void test_foo_mock_with_const (void)"

.PP
Definition at line 34 of file test_foo\&.c\&.
.SS "void test_foo_mock_with_variable_args (void)"

.PP
Definition at line 42 of file test_foo\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
