.TH "Tests/test_mpbTimeBase.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_mpbTimeBase.c
.SH SYNOPSIS
.br
.PP
\fC#include 'unity\&.h'\fP
.br
\fC#include 'mpblibs\&.h'\fP
.br
\fC#include 'mpbTimeBase\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBtest_eMpbTimeBaseInit_InvalidParam_Fail\fP ()"
.br
.ti -1c
.RI "void \fBtest_eMpbTimeBaseInit_Success\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBeMpbError_t\fP \fBeMpbError\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
juan 
.RE
.PP
\fBDate\fP
.RS 4
Created on 2021-11-17 
.RE
.PP
\fBNote\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
MPB, Montreal, Qc 
.SS "(C) COPYRIGHT 2021 MPB, Montreal, Quebec, Canada"
.RE
.PP
.SS "(C) All rights reserved\&."
.PP

.br

.br
 This document contains confidential and proprietary information of MPB (subject to a non-disclosure agreement) and shall not be disclosed, distributed, or reproduced in whole or in part, without the prior written authorization of MPB\&. 
.PP
Definition in file \fBtest_mpbTimeBase\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void setUp (void)"

.PP
Definition at line 31 of file test_mpbTimeBase\&.c\&.
.SS "void tearDown (void)"

.PP
Definition at line 36 of file test_mpbTimeBase\&.c\&.
.SS "void test_eMpbTimeBaseInit_InvalidParam_Fail ()"

.PP
Definition at line 45 of file test_mpbTimeBase\&.c\&.
.SS "void test_eMpbTimeBaseInit_Success ()"

.PP
Definition at line 61 of file test_mpbTimeBase\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBeMpbError_t\fP eMpbError"

.PP
Definition at line 25 of file test_mpbTimeBase\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
