.TH "UnitTestFramework/vendor/ceedling/vendor/unity/auto/unity_test_summary.py" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/vendor/unity/auto/unity_test_summary.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUnityTestSummary\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBunity_test_summary\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fButs\fP = UnityTestSummary()"
.br
.ti -1c
.RI "\fBtargets_dir\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "\fBtargets\fP = list(map(lambda x: x\&.replace('\\\\', '/'), glob(targets_dir + '*\&.test*')))"
.br
.ti -1c
.RI "\fBroot_path\fP = sys\&.argv[2]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
