.TH "UnityTestSummary" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityTestSummary
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.ti -1c
.RI "def \fBset_targets\fP (self, target_array)"
.br
.ti -1c
.RI "def \fBset_root_path\fP (self, path)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBusage\fP (err_msg=None)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBreport\fP"
.br
.ti -1c
.RI "\fBtotal_tests\fP"
.br
.ti -1c
.RI "\fBfailures\fP"
.br
.ti -1c
.RI "\fBignored\fP"
.br
.ti -1c
.RI "\fBtargets\fP"
.br
.ti -1c
.RI "\fBroot\fP"
.br
.ti -1c
.RI "\fBtest_suites\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file unity_to_junit\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self)"

.PP
Definition at line 10 of file unity_to_junit\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def run ( self)"

.PP
Definition at line 19 of file unity_to_junit\&.py\&.
.SS "def set_root_path ( self,  path)"

.PP
Definition at line 107 of file unity_to_junit\&.py\&.
.SS "def set_targets ( self,  target_array)"

.PP
Definition at line 104 of file unity_to_junit\&.py\&.
.SS "def usage ( err_msg = \fCNone\fP)\fC [static]\fP"

.PP
Definition at line 111 of file unity_to_junit\&.py\&.
.SH "Field Documentation"
.PP 
.SS "failures"

.PP
Definition at line 13 of file unity_to_junit\&.py\&.
.SS "ignored"

.PP
Definition at line 14 of file unity_to_junit\&.py\&.
.SS "report"

.PP
Definition at line 11 of file unity_to_junit\&.py\&.
.SS "root"

.PP
Definition at line 16 of file unity_to_junit\&.py\&.
.SS "targets"

.PP
Definition at line 15 of file unity_to_junit\&.py\&.
.SS "test_suites"

.PP
Definition at line 17 of file unity_to_junit\&.py\&.
.SS "total_tests"

.PP
Definition at line 12 of file unity_to_junit\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
