.TH "unity_to_junit" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unity_to_junit
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUnityTestSummary\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fButs\fP = \fBUnityTestSummary\fP()"
.br
.ti -1c
.RI "\fBtargets_dir\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "\fBtargets\fP = list(map(lambda x: x\&.replace('\\\\', '/'), glob(\fBtargets_dir\fP + '*\&.test*')))"
.br
.ti -1c
.RI "\fBroot_path\fP = sys\&.argv[2]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "root_path = sys\&.argv[2]"

.PP
Definition at line 138 of file unity_to_junit\&.py\&.
.SS "targets = list(map(lambda x: x\&.replace('\\\\', '/'), glob(\fBtargets_dir\fP + '*\&.test*')))"

.PP
Definition at line 131 of file unity_to_junit\&.py\&.
.SS "string targets_dir = sys\&.argv[1]"

.PP
Definition at line 128 of file unity_to_junit\&.py\&.
.SS "uts = \fBUnityTestSummary\fP()"

.PP
Definition at line 124 of file unity_to_junit\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
