.TH "UNITY_STORAGE_T" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNITY_STORAGE_T
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unity_internals\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBTestFile\fP"
.br
.ti -1c
.RI "const char * \fBCurrentTestName\fP"
.br
.ti -1c
.RI "const char * \fBCurrentDetail1\fP"
.br
.ti -1c
.RI "const char * \fBCurrentDetail2\fP"
.br
.ti -1c
.RI "\fBUNITY_LINE_TYPE\fP \fBCurrentTestLineNumber\fP"
.br
.ti -1c
.RI "\fBUNITY_COUNTER_TYPE\fP \fBNumberOfTests\fP"
.br
.ti -1c
.RI "\fBUNITY_COUNTER_TYPE\fP \fBTestFailures\fP"
.br
.ti -1c
.RI "\fBUNITY_COUNTER_TYPE\fP \fBTestIgnores\fP"
.br
.ti -1c
.RI "\fBUNITY_COUNTER_TYPE\fP \fBCurrentTestFailed\fP"
.br
.ti -1c
.RI "\fBUNITY_COUNTER_TYPE\fP \fBCurrentTestIgnored\fP"
.br
.ti -1c
.RI "jmp_buf \fBAbortFrame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 427 of file unity_internals\&.h\&.
.SH "Field Documentation"
.PP 
.SS "jmp_buf AbortFrame"

.PP
Definition at line 446 of file unity_internals\&.h\&.
.SS "const char* CurrentDetail1"

.PP
Definition at line 432 of file unity_internals\&.h\&.
.SS "const char* CurrentDetail2"

.PP
Definition at line 433 of file unity_internals\&.h\&.
.SS "\fBUNITY_COUNTER_TYPE\fP CurrentTestFailed"

.PP
Definition at line 439 of file unity_internals\&.h\&.
.SS "\fBUNITY_COUNTER_TYPE\fP CurrentTestIgnored"

.PP
Definition at line 440 of file unity_internals\&.h\&.
.SS "\fBUNITY_LINE_TYPE\fP CurrentTestLineNumber"

.PP
Definition at line 435 of file unity_internals\&.h\&.
.SS "const char* CurrentTestName"

.PP
Definition at line 430 of file unity_internals\&.h\&.
.SS "\fBUNITY_COUNTER_TYPE\fP NumberOfTests"

.PP
Definition at line 436 of file unity_internals\&.h\&.
.SS "\fBUNITY_COUNTER_TYPE\fP TestFailures"

.PP
Definition at line 437 of file unity_internals\&.h\&.
.SS "const char* TestFile"

.PP
Definition at line 429 of file unity_internals\&.h\&.
.SS "\fBUNITY_COUNTER_TYPE\fP TestIgnores"

.PP
Definition at line 438 of file unity_internals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
