.TH "UnityTestSummary" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityTestSummary
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.ti -1c
.RI "def \fBset_targets\fP (self, target_array)"
.br
.ti -1c
.RI "def \fBset_root_path\fP (self, path)"
.br
.ti -1c
.RI "def \fBusage\fP (self, err_msg=None)"
.br
.ti -1c
.RI "def \fBget_details\fP (self, result_file, lines)"
.br
.ti -1c
.RI "def \fBparse_test_summary\fP (self, summary)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBreport\fP"
.br
.ti -1c
.RI "\fBtotal_tests\fP"
.br
.ti -1c
.RI "\fBfailures\fP"
.br
.ti -1c
.RI "\fBignored\fP"
.br
.ti -1c
.RI "\fBtargets\fP"
.br
.ti -1c
.RI "\fBroot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file unity_test_summary\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self)"

.PP
Definition at line 14 of file unity_test_summary\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def get_details ( self,  result_file,  lines)"

.PP
Definition at line 85 of file unity_test_summary\&.py\&.
.SS "def parse_test_summary ( self,  summary)"

.PP
Definition at line 108 of file unity_test_summary\&.py\&.
.SS "def run ( self)"

.PP
Definition at line 20 of file unity_test_summary\&.py\&.
.SS "def set_root_path ( self,  path)"

.PP
Definition at line 71 of file unity_test_summary\&.py\&.
.SS "def set_targets ( self,  target_array)"

.PP
Definition at line 68 of file unity_test_summary\&.py\&.
.SS "def usage ( self,  err_msg = \fCNone\fP)"

.PP
Definition at line 74 of file unity_test_summary\&.py\&.
.SH "Field Documentation"
.PP 
.SS "failures"

.PP
Definition at line 17 of file unity_test_summary\&.py\&.
.SS "ignored"

.PP
Definition at line 18 of file unity_test_summary\&.py\&.
.SS "report"

.PP
Definition at line 15 of file unity_test_summary\&.py\&.
.SS "root"

.PP
Definition at line 72 of file unity_test_summary\&.py\&.
.SS "targets"

.PP
Definition at line 69 of file unity_test_summary\&.py\&.
.SS "total_tests"

.PP
Definition at line 16 of file unity_test_summary\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
