.TH "UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/subfolder/zzz.h" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestFramework/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/subfolder/zzz.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBzzz_sleep\fP (int time, char *name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int zzz_sleep (int time, char * name)"

.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
