.TH "Sources Directory Reference" 3 "Tue Nov 23 2021" "mpbDebouncing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmpbMathDebounce\&.c\fP"
.br
.RI "
.br
 This library provides a management system for the debouncing of digital inputs\&. "
.in -1c
