.TH "Sources/nepMathCoerce.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/nepMathCoerce.c \- Library to coerce values\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nepMathCoerce\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBxNepMathCoerceFloat\fP (float xMinimum, float xMaximum, float xValue)"
.br
.RI "\fI----------------------------------------------------------------------------\fP/ "
.in -1c
.SH "Detailed Description"
.PP 
Library to coerce values\&. 


.PP
\fBAuthor\fP
.RS 4
Mikael Plouffe 
.RE
.PP
\fBDate\fP
.RS 4
Created on 2019-04-25 
.RE
.PP
\fBNote\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
NEP, Montreal, Qc 
.SS "(C) COPYRIGHT 2015 NEP, Montreal, Quebec, Canada"
.RE
.PP
.SS "(C) All rights reserved\&."
.PP

.br

.br
 This document contains confidential and proprietary information of NEPTRONIC (subject to a non-disclosure agreement) and shall not be disclosed, distributed, or reproduced in whole or in part, without the prior written authorization of NEPTRONIC\&. 
.PP
Definition in file \fBnepMathCoerce\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "float xNepMathCoerceFloat (float xMinimum, float xMaximum, float xValue)"

.PP
\fI----------------------------------------------------------------------------\fP/ 
.PP
Definition at line 71 of file nepMathCoerce\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
