.TH "Sources/nepMathRound.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/nepMathRound.c \- Library to calculate the rounding of a value\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nepMathRound\&.h'\fP
.br
\fC#include 'nepMathDivision\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "eNepError_t \fBeNepMathRoundToPrecisionFloat\fP (float *fValue, uint64_t ullPrecision)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library to calculate the rounding of a value\&. 


.PP
\fBAuthor\fP
.RS 4
Mikael Plouffe 
.RE
.PP
\fBDate\fP
.RS 4
Created on 2019-04-25 
.RE
.PP
\fBNote\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
NEP, Montreal, Qc 
.SS "(C) COPYRIGHT 2015 NEP, Montreal, Quebec, Canada"
.RE
.PP
.SS "(C) All rights reserved\&."
.PP

.br

.br
 This document contains confidential and proprietary information of NEPTRONIC (subject to a non-disclosure agreement) and shall not be disclosed, distributed, or reproduced in whole or in part, without the prior written authorization of NEPTRONIC\&. 
.PP
Definition in file \fBnepMathRound\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "eNepError_t eNepMathRoundToPrecisionFloat (float * fValue, uint64_t ullPrecision)"

.PP
Definition at line 132 of file nepMathRound\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
