.TH "Sources/nepMathParity.c" 3 "Thu Nov 18 2021" "mpbTime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/nepMathParity.c
.SH SYNOPSIS
.br
.PP
\fC#include 'nepMathParity\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUMBER_OF_BITS_IN_A_BYTE\fP   ( 8 )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "eNepError_t \fBeNepMathParityCalcul\fP (uint8_t *pucBinaryNumber, uint32_t ulNumberOfBytes, eParityType_t eParityType, eBool_t *pbResponse)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Philippe Boulais 
.RE
.PP
\fBDate\fP
.RS 4
Created on 2019-06-07 
.RE
.PP
\fBCopyright\fP
.RS 4
NEP, Montreal, Qc 
.SS "(C) COPYRIGHT 2015 NEP, Montreal, Quebec, Canada"
.RE
.PP
.SS "(C) All rights reserved\&."
.PP

.br

.br
 This document contains confidential and proprietary information of NEPTRONIC (subject to a non-disclosure agreement) and shall not be disclosed, distributed, or reproduced in whole or in part, without the prior written authorization of NEPTRONIC\&. 
.PP
Definition in file \fBnepMathParity\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define NUMBER_OF_BITS_IN_A_BYTE   ( 8 )"

.PP
Definition at line 17 of file nepMathParity\&.c\&.
.SH "Function Documentation"
.PP 
.SS "eNepError_t eNepMathParityCalcul (uint8_t * pucBinaryNumber, uint32_t ulNumberOfBytes, eParityType_t eParityType, eBool_t * pbResponse)"

.PP
Definition at line 27 of file nepMathParity\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mpbTime from the source code\&.
