display.c
void display_turnOffStatusLed(void)
Referenced by event_deviceReset, test_whenTheDeviceIsReset_thenTheStatusLedIsTurnedOff, test_whenThePowerReadingIsLessThan5_thenTheStatusLedIsNotTurnedOn.