display.h
void display_turnOffStatusLed(void)
Referenced by event_deviceReset, test_whenTheDeviceIsReset_thenTheStatusLedIsTurnedOff, test_whenThePowerReadingIsLessThan5_thenTheStatusLedIsNotTurnedOn.
void display_turnOnStatusLed(void)
Referenced by event_powerReadingUpdate.
void display_setVolume(int level)
Referenced by event_volumeKnobMaxed, test_whenTheVolumeKnobIsMaxed_thenVolumeDisplayIsSetTo11.
void display_setModeToMinimum(void)
Referenced by event_modeSelectButtonPressed, test_whenTheModeSelectButtonIsPressed_thenTheDisplayModeIsCycled.
void display_setModeToMaximum(void)
Referenced by event_modeSelectButtonPressed, test_whenTheModeSelectButtonIsPressed_thenTheDisplayModeIsCycled.
void display_setModeToAverage(void)
Referenced by event_modeSelectButtonPressed, test_whenTheModeSelectButtonIsPressed_thenTheDisplayModeIsCycled.
bool display_isError(void)
Referenced by event_devicePoweredOn.
void display_powerDown(void)
Referenced by event_devicePoweredOn, event_keyboardCheckTimerExpired, test_givenTheDisplayHasAnError_whenTheDeviceIsPoweredOn_thenTheDisplayIsPoweredDown, test_givenTheUserHasTypedSleep_whenItIsTimeToCheckTheKeyboard_theDisplayIsPoweredDown.
void display_updateData(int data, void(*updateCompleteCallback)(void))
void display_getKeyboardEntry(char *entry, int length)
Referenced by event_keyboardCheckTimerExpired.