foo.c
void foo_turn_on(void)
References bar_turn_on, zzz_sleep.
Referenced by test_foo, test_foo_again.
void foo_print_message(const char *message)
References bar_print_message.
Referenced by test_foo_mock_with_const.
void foo_print_special_message(void)
References bar_print_message_formatted.
Referenced by test_foo_mock_with_variable_args.