nepMathDivision.c
float vroundf(float var)
Referenced by eNepMathDivisionDouble, eNepMathDivisionFloat.
eNepError_t eNepMathDivisionU32(uint32_t ulNumerator, uint32_t ulDenominator, uint32_t *pulResult)
Referenced by eNepMathResistorGetEquivalentInParallel, eNepMathResistorGetResistorInParallel, eNepMathResistorVoltageDividerGetPullDownResistor, eNepMathResistorVoltageDividerGetPullUpResistor, eNepMathResistorVoltageDividerGetVin, eNepMathResistorVoltageDividerGetVout.
eNepError_t eNepMathDivisionFloat(float fNumerator, float fDenominator, float *pfResult)
References vroundf.
Referenced by eNepMathLinearApproxFloat, eNepMathOpAmpGetOutputVoltage, eNepMathResistorFloatVoltageDividerGetPullDownResistor, eNepMathResistorFloatVoltageDividerGetPullUpResistor, eNepMathResistorFloatVoltageDividerGetVin, eNepMathResistorFloatVoltageDividerGetVout, eNepMathRoundToPrecisionFloat.
eNepError_t eNepMathDivisionDouble(double fdNumerator, double fdDenominator, double *pdfResult)
References vroundf.
Referenced by eNepMathAverageFloat.
eNepError_t eNepMathDivisionS64(int64_t sllNumerator, int64_t sllDenominator, int64_t *psllResult)
Referenced by eNepMathAverageS32.