bar.h
void bar_turn_on(void)
Referenced by foo_turn_on.
void bar_print_message(const char *message)
Referenced by foo_print_message.
void bar_print_message_formatted(const char *format,...)
Referenced by foo_print_special_message.
void bar_numbers(int one, int two, char three)
void bar_const_test(const char *a, char *const b, const int c)
custom_t bar_needs_custom_type(void)
const char* bar_return_const_ptr(int one)